# Site settings
title: Washington Park Hotel South Beach | Miami Beach, FL
email:  wphreservations@wphsouthbeach.com
phone:  (305) 421-6265
description: > # this means to ignore newlines until "baseurl:"
 Washington Park Hotel South Beach is located in the heart of South Beach just two blocks from Miami Beach, FL and a half mile from Lincoln Road and the SoFi District. Visit our website for exclusive specials and booking offers.

permalink: pretty
 
default_lang: 'en'
languages: ['en'] 
url: "http://yourdomain.com" # the base hostname & protocol for your site

exclude:
  - 'sitemap.json'


port: 4001

keep_files: ['assets']
rsync_copy: ['_assets']
permalink: /blog/:year/:month/:day/:title
gems: [jekyll-paginate]

# Build settings
paginate: 3
paginate_path: "/blog/page:num/"
markdown: kramdown
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"